# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

title: blank # the website title (if blank, full name will be used instead)
first_name: Dhanesh Baalaji
middle_name:
last_name: Srinivasan
contact_note:
description: > # the ">" symbol means to ignore newlines until "footer_text:"
  Full Stack Engineering | Machine Learning Systems and Infrastructure
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank">Jekyll</a> with <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.
keywords: jekyll, jekyll-theme, academic-website, portfolio-website # add your own keywords or leave empty
lang: en # the language of your site (for example: en, fr, cn, ru, etc.)
icon: code.png # the emoji used as the favicon (alternatively, provide image name in /assets/img/)

url: https://dyanb.github.io # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/. Leave blank for root
last_updated: false # set to true if you want to display last updated in the footer
impressum_path: # set to path to include impressum link in the footer, use the same path as permalink in a page, helps to conform with EU GDPR
back_to_top: true # set to false to disable the back to top button


# -----------------------------------------------------------------------------
# Layout
# -----------------------------------------------------------------------------

navbar_fixed: true
footer_fixed: true
search_enabled: false
socials_in_search: true
posts_in_search: true
bib_search: true

# Dimensions
max_width: 930px

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------

blog_name: Dhanesh's Blog # blog_name will be displayed in your blog page
blog_description: ""
permalink: /blog/:year/:title/
lsi: false # produce an index for related posts

# Pagination
paginate: 10
paginate_path: "/blog/page:num/"

related_blog_posts:
  enabled: true
  max_related: 5


# External sources.
# If you have blog posts published on medium.com or other external sources,
# you can display them in your blog by adding a link to the RSS feed.

# COMMENTING THIS FOR NOW - NOT PUBLISHED ANYTHING IN MEDIUM
# external_sources:
#   - name: medium.com
#     rss_url: https://medium.com/@al-folio/feed


# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  news:
    defaults:
      layout: post
    output: true
  projects:
    output: true

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Markdown and syntax highlight
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  toc_levels: 1..6
  auto_ids: true
  hard_wrap: false
  syntax_highlighter_opts:
    css_class: "highlight"
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# Includes & excludes
include: ["_pages"]
exclude:
  - bin/
  - CONTRIBUTING.md
  - CUSTOMIZE.md
  - Dockerfile
  - docker-compose.yml
  - docker-compose-slim.yml
  - FAQ.md
  - Gemfile
  - Gemfile.lock
  - INSTALL.md
  - LICENSE
  - lighthouse_results/
  - package.json
  - package-lock.json
  - _pages/about_einstein.md
  - purgecss.config.js
  - README.md
  - readme_preview/
  - vendor
keep_files:
  - CNAME
  - .nojekyll

# Plug-ins
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-scholar
  - jekyll-email-protect
  - jemoji

sass:
  style: compressed

imagemagick:
  enabled: false

# -----------------------------------------------------------------------------
# Optional Features
# -----------------------------------------------------------------------------

enable_masonry: true # enables automatic project cards arrangement
enable_math: true # enables math typesetting (uses MathJax)
enable_darkmode: true # enables switching between light/dark modes
enable_medium_zoom: true # enables image zoom feature (as on medium.com)
enable_progressbar: true # enables a horizontal progress bar linked to the vertical scroll position
third_party_libraries: {}